# Generated by Django 6.0.3 on 2026-04-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_category_comments_readlaterblog_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
    ]
